### ISSUE TITLE
你是用什么GO什么版本的 我这抱一堆错误

### ISSUE THREAD

**Issue by leisure520** [CodyGuo/xcgui#5]
panic: Failed to load XCGUI.dll: %1 is not a valid Win32 application.

goroutine 1 [running, locked to thread]:
syscall.MustLoadDLL(0x770af7, 0x9, 0x45b301)
	C:/Go/src/syscall/dll_windows.go:77 +0x73
github.com/codyguo/xcgui/xc.init.1()
	C:/Go/src/github.com/codyguo/xcgui/xc/aapi.go:79 +0xf1
github.com/codyguo/xcgui/xc.init()
	C:/Go/src/github.com/codyguo/xcgui/xc/xwm.go:457 +0x81
main.init()
	C:/Go/src/github.com/codyguo/xcgui/examples/comboBox/comboBox.go:31 +0x50

win7
好像是DLL的调用出错，是不是GO1.8后出现新的DLL方式去调用？

**Comment by CodyGuo** [comment]
这dll只支持32位的。
友情提醒：64位编译环境下需要设置 set GOARCH=386。

**Comment by sndnvaps** [comment]
用32位的 go就可以了。

**Comment by zhongxiaole** [comment]
我设置GOARCH=386  但是还是会出现一楼提的问题，这是我的GO版本问题吗，还是DLL又有更新的问题
